apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: service-deployment-cluster-role
  namespace: cloud-sud-nginx-operator
rules:
  - apiGroups:
    - ""
    resources:
    - secrets
    - serviceaccounts
    - services  
    verbs:
    - "*"
  - apiGroups:
    - "apps"
    verbs:
      - "*"
    resources:
    - deployments
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: service-deployment-cluster-role-binding
  namespace: cloud-sud-nginx-operator
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: service-deployment-cluster-role
subjects:
  - kind: ServiceAccount
    name: cloud-sud-nginx-operator
    namespace: cloud-sud-nginx-operator
---
